sudo: false
language: java
cache:
  directories:
    - $HOME/.m2
env:
  global:
    - DISPLAY=:99.0
before_install:
  - sh -e /etc/init.d/xvfb start - sleep 10

//override Travis default mvn install step
install: true

script:
  - mvn clean verify
notifications:
  email:
    - fbricon@gmail.com
