dist: xenial
sudo: false
language: java
services:
  - xvfb
jdk:
  - openjdk8
cache:
  directories:
    - $HOME/.m2
# no-op to override Travis' default `mvn install` step
install: true

script:
  - mvn clean verify
notifications:
  email:
    - fbricon@gmail.com
