name: Tycho Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'maven'

    - name: Build with Maven
      run: >
        xvfb-run
        ./mvnw -B verify
        
    - name: Deploy snapshot p2 repo to Github Pages
      if: ${{ github.ref == 'ref/head/master' }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ github.token }}
        publish_dir: ./org.jboss.tools.maven.apt.site/target/repository
        destination_dir: snapshots/