name: Publish Update Site

on:
  push:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'maven'

    - name: Build with Maven
      run: |
        xvfb-run \
        ./mvnw -B verify
        version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "PROJECT_VERSION=${version%"-SNAPSHOT"}" >> $GITHUB_ENV

    - name: Deploy versionned p2 repo to Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ github.token }}
        publish_dir: ./org.jboss.tools.maven.apt.site/target/repository
        destination_dir: updates/${{ env.PROJECT_VERSION }}
        
    - name: Deploy latest p2 repo to Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ github.token }}
        publish_dir: ./org.jboss.tools.maven.apt.site/target/repository
        destination_dir: latest/